package com.noturingback.tradinglearning.domain.enumeration;

/**
 * The Categorie enumeration.
 */
public enum Categorie {
    AGRICULTURE,ANIMALIER,BATIMENT,COMMUNICATION,CULTURE,DROIT,EDUCATION,ENERGIE,FINANCE,INDUSTRIE,INFORMATIQUE,INGENIERIE,LOGISTIQUE,MANAGEMENT,MECANIQUE,MEDIAS,MILITAIRE,MODE,NATURE,RECHERCHE,SANTE,SERVICE,SOCIAL,SPORT,TRANSPORT
}
